[package]
name = "axdriver_input"
edition.workspace = true
version.workspace = true
authors.workspace = true
description = "Common traits and types for input device drivers"
documentation = "https://arceos-org.github.io/axdriver_crates/axdriver_input"
keywords = ["arceos", "driver", "input"]
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
axdriver_base = { version = "0.1.3-preview.1" }
strum = { version = "0.27.2", default-features = false, features = ["derive"] }
