[package]
name = "axdriver_display"
edition.workspace = true
version.workspace = true
authors.workspace = true
description = "Common traits and types for graphics device drivers"
documentation = "https://arceos-org.github.io/axdriver_crates/axdriver_display"
keywords = ["arceos", "driver", "gpu", "framebuffer"]
license.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
axdriver_base = { version = "0.1.3-preview.1" }
